[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
fs_permissions = [{ access = "read-write", path = "./out" }]
solc = '0.8.22'
evm_version='paris'
test = 'test'
optimizer = true
optimizer_runs = 100
ignored_error_codes = []

[fmt]
line_length = 115
wrap_comments = true

[rpc_endpoints]
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
