#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'yarn-lock.json'; then
  echo "Lockfile changes detected. Installing updates..."
  yarn install
fi
